# Generated by Django 4.1.4 on 2023-01-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://via.placeholder.com/240x240x.jpg', null=True, upload_to='uploads/annoces_images/'),
        ),
    ]
