# Generated by Django 4.1.4 on 2022-12-24 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('espaceannonce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('tarif', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='espaceannonce.category')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='espaceannonce.commune')),
                ('modalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='espaceannonce.modalité')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='espaceannonce.theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='espaceannonce.wilaya')),
            ],
        ),
    ]
