# Generated by Django 4.1.4 on 2022-12-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaceannonce', '0003_annonce_date_modif'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='addresse',
            field=models.TextField(default='', max_length=70),
        ),
    ]
