# Generated by Django 4.1.4 on 2022-12-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaceannonce', '0004_annonce_addresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/annoces_images/'),
        ),
    ]
