# Generated by Django 4.1.4 on 2022-12-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaceannonce', '0005_annonce_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/annoces_images/thumbnail'),
        ),
    ]
