# Generated by Django 4.1.4 on 2023-01-07 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espaceannonce', '0007_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='annonc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='espaceannonce.annonce'),
        ),
    ]
