# Generated by Django 4.1.4 on 2023-01-07 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espaceannonce', '0008_alter_offer_annonc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Communes', to='espaceannonce.wilaya'),
        ),
    ]
