# Generated by Django 4.1.4 on 2023-01-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espaceannonce', '0010_messageann'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
    ]
